name: update
on:
 schedule:
   - cron: "30 6 * * 1-5"
 workflow_dispatch:
jobs:
 update:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v4
   - uses: actions/setup-python@v5
   - run: python generate_daily_v3.py
